### ISSUE TITLE
Cannot read project manifest -- Cause: Remote resource not found

### ISSUE THREAD

**Issue by xiadawei123** [Popgen48/scalepopgen_v1#2] opened 2024-03-30 14:48 UTC
### Description of the bug

Hi, after resolving the network connection issue, I ran the test command again, but it seems that I still cannot get the results from scalepopgen. I suspect it might still be a network issue, but I can access Google normally. I'm confused and would appreciate your assistance.

### Command used and terminal output

```console
$ nextflow run scalepopgen -profile test,conda -qs 10
N E X T F L O W  ~  version 23.10.1
Pulling nextflow-io/scalepopgen ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nextflow-io/scalepopgen/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nextflow-io/scalepopgen/contents/main.nf
```

**Comment by BioInf2305** [comment] 2024-04-02 11:50
Hello, thank you for trying out the workflow. When you run `nextflow run scalepopgen -profile test,conda -qs 10` it looks for the "scalepopgen" directory inside the nf-core repository, and it could not find the repo there. Try running this command `nextflow run popgen48/scalepopgen -profile test,conda -qs 10`, this should work then.

**Comment by BioInf2305** [comment] 2024-04-02 11:54
I will close this issue as it is not a bug. But feel free to open an issue if you still come across any error.

**Closed as completed by BioInf2305** 2024-04-02 11:54 UTC
Labels: invalid
